### ISSUE TITLE
MacOS运行服务器找不到 kcp.lib

### ISSUE THREAD

**Issue by lovexbma** [FlameskyDexive/Legends-Of-Heroes#10]
System.TypeInitializationException: The type initializer for 'ET.KService' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'kcp' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 

Legends-Of-Heroes-ET7.2/Bin/runtimes/osx
这个目录中有 libkcp.dylib

系统版本：14.4
CPU:M2

**Comment by FlameskyDexive** [comment]
7.2分支的kcp需要自己编译下mac os的库，ET8之后的kcp是纯C#实现，建议看主干分支的代码。
