### ISSUE TITLE
TemplateMultiKeys 有个问题

### ISSUE THREAD

**Issue by bloneedu** [FlameskyDexive/Legends-Of-Heroes#2]
TemplateMultiKeys.txt里有个小错误
第22行 foreach ((ConfigName) config in list)
应该是 foreach ((ConfigName) config in s.list)

不然在多个key时，生成的catagory里的dict会有问题

**Comment by FlameskyDexive** [comment]
嗯，master上的这个模板确实有误，多谢指正，已经修复提交。从7.2升级到ET8的过程中漏掉了，主干游戏内逻辑还没接完。
