### ISSUE TITLE
FixedUpdate 在 ThreadScheduler 和 ThreadPoolScheduler 线程里好像不是固定间隔

### ISSUE THREAD

**Issue by Lead-NorthStar** [FlameskyDexive/Legends-Of-Heroes#5]
FixedUpdate 只有 MainThreadScheduler 是通过 FixedUpdate 单例的回调实现了固定时间间隔刷新，【World.Instance.AddSingleton<FixedUpdate, Action>(FixedUpdate);】

而 ThreadScheduler 和 ThreadPoolScheduler 好像都是直接在 Thread 的  while 循环里和 Update 一样调用了，没有走 Xenko 的固定时间间隔刷新器里的流程。

**Comment by FlameskyDexive** [comment]
> FixedUpdate 只有 MainThreadScheduler 是通过 FixedUpdate 单例的回调实现了固定时间间隔刷新，【World.Instance.AddSingleton<FixedUpdate, Action>(FixedUpdate);】
> 
> 而 ThreadScheduler 和 ThreadPoolScheduler 好像都是直接在 Thread 的 while 循环里和 Update 一样调用了，没有走 Xenko 的固定时间间隔刷新器里的流程。

多线程跟线程池的fiber是有问题，已经提交添加了一个做法处理，你可以看下RobotCaseComponentSystem下FixedUpdate方法，开启日志，用命令（dotnet App.dll --Console=1）启动server，查看控制台打印的当前时间戳（ms）间隔。 有异常或者有其他思路麻烦给我反馈哈
