### ISSUE TITLE
#if UNITY_EDITOR 这个宏在 ET 框架中无法使用

### ISSUE THREAD

**Issue by Lead-NorthStar** [FlameskyDexive/Legends-Of-Heroes#6]
![图片](https://github.com/FlameskyDexive/Legends-Of-Heroes/assets/139985926/1a0794eb-a1b9-4b88-97d5-5469db037241)
UNITY_EDITOR 宏在 ET 框架中无法正常使用，目前只能在客户端 View 部分使用 Define.IsEditor 来判断。
![图片](https://github.com/FlameskyDexive/Legends-Of-Heroes/assets/139985926/dec5dfe6-ebb7-4f2b-8057-32d76d7f1719)

**Comment by FlameskyDexive** [comment]
DefineCore是划分于Core的程序集，Define是划分在客户端Loader的程序集，#if UNITY_EDITOR可以在代码中使用，dotnet的程序集不生效，unity下的程序集生效。  Define.IsEditor这个仅仅只能在客户端代码使用，程序集划分限制了。

**Comment by FlameskyDexive** [comment]
![image](https://github.com/FlameskyDexive/Legends-Of-Heroes/assets/8274346/87647d64-bc2f-41bc-8b5c-7fb57940f0bd)
DotNet工程下不生效
![image](https://github.com/FlameskyDexive/Legends-Of-Heroes/assets/8274346/eaf701fe-61db-4698-a5ad-9ea6fb0a375d)
Unity工程下生效

**Comment by Lead-NorthStar** [comment]
原来如此，平常都是开的 ET.sln，谢谢
