### ISSUE TITLE
跑不起来，请问还需要怎么配置呢

### ISSUE THREAD

**Issue by christan-duplicate** [FlameskyDexive/Legends-Of-Heroes#8]
![image](https://github.com/FlameskyDexive/Legends-Of-Heroes/assets/769138/5a7e91fd-3b21-4e00-a38c-c56a6c69c60d)

**Comment by FlameskyDexive** [comment]
先打开ET.sln，编译一下SourceGenerator库文件

**Comment by christan-duplicate** [comment]
> 先打开ET.sln，编译一下SourceGenerator库文件

你好，我就是先编译SourceGenerator，这一步是正常的，但是再编译DotNet.App的时候，就报上面的错了

**Comment by FlameskyDexive** [comment]
> > 先打开ET.sln，编译一下SourceGenerator库文件
> 
> 你好，我就是先编译SourceGenerator，这一步是正常的，但是再编译DotNet.App的时候，就报上面的错了

更新，SG项目误同步了ET Dev分支的库变成了2.1， 现在改成2.0，测试已正常编译

**Comment by christan-duplicate** [comment]
> > > 先打开ET.sln，编译一下SourceGenerator库文件
> > 
> > 
> > 你好，我就是先编译SourceGenerator，这一步是正常的，但是再编译DotNet.App的时候，就报上面的错了
> 
> 更新，SG项目误同步了ET Dev分支的库变成了2.1， 现在改成2.0，测试已正常编译

感谢大神，重新拉取代码后，能跑起来的！！！
